server:
  port: 8686
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sec_kill?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379
    password: root123456
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 10
        max-wait: 1000ms

  freemarker:
    template-loader-path=classpath: /templates
    cache: false
    charset: UTF-8
    suffix: .ftl

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        #定义消费者做多同时处理10个消息
        prefetch: 10
        #消息手动确认
        acknowledge-mode: manual

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true